In [41]:
from google.colab import drive
drive.mount("/content/drive")
import pandas as pd
import numpy as np
pd.__version__

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


'1.3.5'

In [42]:
%cd "/content/drive/MyDrive/Programming/Pz/Data_analysis_python_pandas/db"
!ls

/content/drive/MyDrive/Programming/Pz/Data_analysis_python_pandas/db
API_SP.POP.TOTL_DS2_en_csv_v2_3852487.csv		      test.csv
london_merged.csv					      test.hdf
Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_3852487.csv    test.json
Metadata_Indicator_API_SP.POP.TOTL_DS2_en_csv_v2_3852487.csv  test.parquet
Meteorite_Landings.csv					      test.pkl
poblacion.csv						      test.xlsx


In [43]:
pd.options.display.float_format = "{:.2f}".format
np.set_printoptions(precision=1)

In [ ]:
x1 = np.random.rand(2,5)*10
x1

array([[1.4, 8.8, 7.4, 6. , 9.6],
       [8.9, 0.1, 3. , 6.7, 3. ]])

In [ ]:
x2 = np.random.rand(2,5)*-1

In [ ]:
np.concatenate([x1,x2])

array([[ 1.4,  8.8,  7.4,  6. ,  9.6],
       [ 8.9,  0.1,  3. ,  6.7,  3. ],
       [-0.5, -0.6, -0.7, -0.1, -0.4],
       [-0.7, -0.5, -1. , -0.9, -0.6]])

In [ ]:
np.concatenate([x1,x2]).shape

(4, 5)

In [ ]:
np.concatenate([x1,x2],axis=1)

array([[ 1.4,  8.8,  7.4,  6. ,  9.6, -0.5, -0.6, -0.7, -0.1, -0.4],
       [ 8.9,  0.1,  3. ,  6.7,  3. , -0.7, -0.5, -1. , -0.9, -0.6]])

In [ ]:
s1 = pd.Series(x1[0], index=["a","b","c","d","e"])
s1

a   1.40
b   8.78
c   7.43
d   6.00
e   9.56
dtype: float64

In [ ]:
s2 = pd.Series(x2[0], index=["c","d","e","f","g"])
s2

c   -0.54
d   -0.60
e   -0.74
f   -0.13
g   -0.35
dtype: float64

In [ ]:
pd.concat([s1,s2])

a    1.40
b    8.78
c    7.43
d    6.00
e    9.56
c   -0.54
d   -0.60
e   -0.74
f   -0.13
g   -0.35
dtype: float64

In [ ]:
pd.concat([s1,s2],axis=1)

0     1
a 1.40   NaN
b 8.78   NaN
c 7.43 -0.54
d 6.00 -0.60
e 9.56 -0.74
f  NaN -0.13
g  NaN -0.35

In [ ]:
s1.reset_index(drop=True)

0   1.40
1   8.78
2   7.43
3   6.00
4   9.56
dtype: float64

In [ ]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0     1
0 1.40 -0.54
1 8.78 -0.60
2 7.43 -0.74
3 6.00 -0.13
4 9.56 -0.35

In [ ]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=["a","b"])
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=["a","b"], index=[2,3,4])

In [ ]:
df1

a    b
0 4.86 0.44
1 1.55 3.97
2 2.92 2.34

In [ ]:
df2

a     b
2 -0.54 -0.50
3 -0.25 -0.96
4 -0.80 -0.13

In [ ]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 4.86 0.44   NaN   NaN
1 1.55 3.97   NaN   NaN
2 2.92 2.34 -0.54 -0.50
3  NaN  NaN -0.25 -0.96
4  NaN  NaN -0.80 -0.13

In [ ]:
pd.concat([df1,df2],axis=1,join="inner")

a    b     a     b
2 2.92 2.34 -0.54 -0.50

In [ ]:
pd.concat([df1.reset_index(drop=True),df2.reset_index(drop=True)],axis=1)

a    b     a     b
0 4.86 0.44 -0.54 -0.50
1 1.55 3.97 -0.25 -0.96
2 2.92 2.34 -0.80 -0.13

In [ ]:
df1.append(df2).append(df2)

a     b
0  4.86  0.44
1  1.55  3.97
2  2.92  2.34
2 -0.54 -0.50
3 -0.25 -0.96
4 -0.80 -0.13
2 -0.54 -0.50
3 -0.25 -0.96
4 -0.80 -0.13

In [ ]:
df1.T.append(df2.T).T

a    b     a     b
0 4.86 0.44   NaN   NaN
1 1.55 3.97   NaN   NaN
2 2.92 2.34 -0.54 -0.50
3  NaN  NaN -0.25 -0.96
4  NaN  NaN -0.80 -0.13

In [46]:
df_left = pd.DataFrame(
    {"X":["x0","x1","x2","x3"],
     "W":["w0","w1","w2","w3"],
     "Y":["y0","y1","y2","y3"],
     "MIX":["y2","y3","a2","a3"]},
     index=[0,1,2,3])
df_left

X   W   Y MIX
0  x0  w0  y0  y2
1  x1  w1  y1  y3
2  x2  w2  y2  a2
3  x3  w3  y3  a3

In [45]:
df_right = pd.DataFrame(
    {"Z":["z2","z3","z4","z5"],
     "A":["a2","a3","a4","a5"],
     "Y":["y2","y3","y4","y5"]},
     index=[2,3,4,5]
)
df_right

Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

In [47]:
pd.merge(df_left,df_right)

X   W   Y MIX   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [49]:
pd.merge(df_left,df_right,how="inner",on="Y")

X   W   Y MIX   Z   A
0  x2  w2  y2  a2  z2  a2
1  x3  w3  y3  a3  z3  a3

In [50]:
pd.merge(df_left,df_right,how="inner",left_on="MIX",right_on="Y")

X   W Y_x MIX   Z   A Y_y
0  x0  w0  y0  y2  z2  a2  y2
1  x1  w1  y1  y3  z3  a3  y3

In [51]:
pd.merge(df_left,df_right,how="inner",left_on="MIX",right_on="A")

X   W Y_x MIX   Z   A Y_y
0  x2  w2  y2  a2  z2  a2  y2
1  x3  w3  y3  a3  z3  a3  y3

In [54]:
df_left = pd.DataFrame(
    {"X":["x0","x1","x2","x3"],
     "W":["w0","w1","w2","w3"],
     "Y":["y0","y1","y2","y3"]},
     index=[0,1,2,3])
df_left

X   W   Y
0  x0  w0  y0
1  x1  w1  y1
2  x2  w2  y2
3  x3  w3  y3

In [55]:
df_right = pd.DataFrame(
    {"Z":["z2","z3","z4","z5"],
     "A":["a2","a3","a4","a5"],
     "Y":["y2","y3","y4","y5"]},
     index=[2,3,4,5]
)
df_right

Z   A   Y
2  z2  a2  y2
3  z3  a3  y3
4  z4  a4  y4
5  z5  a5  y5

In [56]:
pd.merge(df_left,df_right,how="inner",on="Y")

X   W   Y   Z   A
0  x2  w2  y2  z2  a2
1  x3  w3  y3  z3  a3

In [57]:
pd.merge(df_left,df_right,how="left",on="Y")

X   W   Y    Z    A
0  x0  w0  y0  NaN  NaN
1  x1  w1  y1  NaN  NaN
2  x2  w2  y2   z2   a2
3  x3  w3  y3   z3   a3

In [58]:
pd.merge(df_left,df_right,how="right",on="Y")

X    W   Y   Z   A
0   x2   w2  y2  z2  a2
1   x3   w3  y3  z3  a3
2  NaN  NaN  y4  z4  a4
3  NaN  NaN  y5  z5  a5

In [59]:
pd.merge(df_left,df_right,how="outer",on="Y")

X    W   Y    Z    A
0   x0   w0  y0  NaN  NaN
1   x1   w1  y1  NaN  NaN
2   x2   w2  y2   z2   a2
3   x3   w3  y3   z3   a3
4  NaN  NaN  y4   z4   a4
5  NaN  NaN  y5   z5   a5

In [65]:
pd.merge(df_left,df_right,how="outer",on="A",sufixes=["_left","_right"])

X    W   Y    Z    A
0   x0   w0  y0  NaN  NaN
1   x1   w1  y1  NaN  NaN
2   x2   w2  y2   z2   a2
3   x3   w3  y3   z3   a3
4  NaN  NaN  y4   z4   a4
5  NaN  NaN  y5   z5   a5